import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { TextStyleKit } from '@tiptap/extension-text-style';
import Highlight from '@tiptap/extension-highlight';
import TextAlign from '@tiptap/extension-text-align';
import { Table, TableCell, TableHeader, TableRow } from '@tiptap/extension-table';
import { useEffect, useRef } from 'react';
import { HandImage } from './extensions';
import { useInkOverlay } from './InkOverlay';
import type { PaperSettings, Typography } from '../types';
import { paperCss } from '../paper';

interface Props {
  styleId: string | null;
  typo: Typography;
  paper: PaperSettings;
  inkEnabled: boolean;
  onEditor: (e: ReturnType<typeof useEditor>) => void;
}

const WELCOME = `
<h1>Your handwriting, powered by AI</h1>
<p>Upload a sample on the left, then just type. Prose is generated by
<b>Paragraph-LDM</b> (zero-shot paragraph imitation) and anything mathematical —
numbers like 42, expressions like $x^2 + y^2 = r^2$, chemistry like H2O —
is routed to <b>DiffInk</b>.</p>
<p>All formatting works on the generated ink: <b>bold</b>, <i>italic</i>,
<u>underline</u>, colors, alignment, lists, tables and images.</p>
`;

export function HandwritingEditor({ styleId, typo, paper, inkEnabled, onEditor }: Props) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const editor = useEditor({
    extensions: [
      StarterKit,
      TextStyleKit,
      Highlight.configure({ multicolor: true }),
      TextAlign.configure({ types: ['heading', 'paragraph'] }),
      Table.configure({ resizable: true }),
      TableRow, TableHeader, TableCell,
      HandImage,
    ],
    content: WELCOME,
  });

  useEffect(() => {
    if (editor && !editor.isDestroyed) onEditor(editor);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editor]);

  useInkOverlay(editor, canvasRef, containerRef, styleId, typo, inkEnabled);

  const mmPad = paper.marginMm * (96 / 25.4) + typo.pagePadding;
  return (
    <div className="page-scroll">
      <div
        ref={containerRef}
        className={`page ${inkEnabled ? 'ink-on' : ''} ${paper.showMarginLine ? 'margin-line' : ''}`}
        style={{
          ...paperCss(paper),
          padding: `${mmPad}px`,
          ['--hw-font-scale' as string]: typo.fontScale,
          ['--hw-line-height' as string]: typo.lineHeight,
          ['--hw-letter-spacing' as string]: `${typo.letterSpacing}px`,
          ['--hw-word-spacing' as string]: `${typo.wordSpacing}px`,
          ['--hw-para-spacing' as string]: `${typo.paragraphSpacing}px`,
        }}
      >
        <EditorContent editor={editor} />
        <canvas ref={canvasRef} className="ink-canvas" />
      </div>
    </div>
  );
}
